# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b76edb070595c7e8a6fbcc980ee8d3acebb9acb4633ee8e478b4884432d58a248813224b96ae6e2d81305c44ec3f521b890f8822382529c3e045ec019c2ffbfc

test:
  secret_key_base: 5019963cd29a3b7a5706f7fba1efe48ece0c746a776c364245822c0ff562240443a96cc5bd95cd10391baa7ee910d83a69860ae9c4ff1d4f56e1311d182e3e14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
